
def sku_grade_map():
    grade_code_map = {
        "A": "AX",
        "A+": "AA",
        "AB": "BX",
        "B": "BX",
        "BC": "CX",
        "C": "CX",
        "C+": "CX",
    }
    
    return grade_code_map


def sku_colour_map():
    colour_code_map = {
        "Gold": "GD",
        "Blue": "BL",
        "Black": "BK",
        "Grey": "GY",
        "Silver": "SL",
        "Space Grey": "GY",
        "Rose Gold": "RG",
        "red": "RD",
        "Orange": "OR",
        "White": "WH",
        "Graphite": "GP",
        "Purple": "PL",
        "Pink": "PK",
        "Green": "GR",
        "Yellow": "YE",
        "Space Gray": "GY",
        "Brown": "BR",
        "twilight": "TW",
        "midnight blue": "BL",
        "gray": "GY",
        "GOLDEN": "GD",
        "Crystal": "CY",
        "Aurora": "AR",
        "Violet": "VL",
        "Cosmic Gray": "CG",
        "Cosmic Black": "BK",
        "Cloud Blue": "CB",
        "Phantom White": "WH",
        "Phantom Gray": "GY",
        "Phantom Pink": "PK",
        "Phantom Silver": "SL",
        "Phantom Black": "BK",
        "Pacific Blue": "PB",
        "Bronze": "BZ",
        "Mystic Blue": "BL",
        "Aura Black": "BK",
        "Aura Glow": "AG",
        "Titanium": "TT",
        "Midnight Green": "GR",
        "Navy": "NV",
        "Lavender": "LV",
        "Breathing Crystal": "BC",
        "Midnight Black": "BK",
        "Ceramic Black": "PK",
        "Cloud Pink": "PK",
        "Phantom Navy": "NV",
        "Coral": "CR",
        "Beige": "BE",
        "Coral Blue": "BL",
        "Phantom Violet": "VL",
        "Phantom Titanium": "TT",
        "Midnight": "MN",
        "Sunrise Gold": "GD",
        "Lilac Purple": "PL",
        "Prism White": "WH",
        "Prism Green": "GR",
        "Prism Blue": "BL",
        "Prism Black": "BK",
        "Prism Silver": "SL",
        "Cardinal Red": "RD",
        "Ceramic White": "WH",
        "Aura White": "WH",
        "Aura Blue": "BL",
        "Starlight": "ST",
        "Nighttime Blue": "BL",
        "Phantom Brown": "BR",
        "Polaris Blue": "BL",
        "Ocean Blue": "BL",
        "Titanium Gray": "GY",
        "Phantom Red": "RD",
        "Prisim Black": "BK",  # Note: "Prisim" may be a typo of "Prism"
        "Sierra Blue": "BL",
        "Phantom Green": "GR",
        "Pink Gold": "PG",
        "Burgundy": "BG",
        "Flamingo Pink": "PK",
        "Light Blue": "BL",
        "Carbon Gray": "GY",
        "Ice Blue": "BL",
        "Alpine Green": "GR",
        "Graphite Gray": "GY",
        "Twilight Blue": "BL",
        "Sea Blue": "BL",
        "Truffle Black": "BK",
        "Cloud White": "WH",
        "Glacier Blue": "BL",
        "Star Blue": "BL",
        "Phantom Purple": "PL",
        "Mint Green": "GR",
        "(PRODUCT) RED": "RD",
        "Lime Gold": "GD",
        "Awesome Black": "BK",
        "Awesome Blue": "BL",
        "Awesome Graphite": "GP",
        "Awesome Lime": "AL",
        "Awesome Peach": "AP",
        "Black Gold": "BG",
        "Black Titanium": "BK",
        "Blue Titanium": "BL",
        "Celestial Blue": "CB",
        "Chrome": "CH",
        "Copper": "CO",
        "Cosmic Grey": "GY",
        "Deep Purple": "PL",
        "Desert Titanium": "DT",
        "Meteorite Gray": "GY",
        "Moonlight White": "WH",
        "Mystic Black": "BK",
        "Natural Titanium": "NT",
        "Onyx Black": "BK",
        "Peacock Blue": "BL",
        "Pearl White": "WH",
        "Polar White": "WH",
        "Prism Cube Black": "BK",
        "Red Black": "RB",
        "Sky Blue": "BL",
        "Space Black": "BK",
        "Titanium Black": "BK",
        "Titanium Silverblue": "BL",
        "White Gold": "WG",
        "Mint": "MT",
        "Teal": "TE",
        "Icelandic Illusion": "IL",
        "Lime": "LI",
        "Jet Black": "BK",
    }
    
    return colour_code_map


def komsa_colour_map():
    colour_map = {
        # longer names first
        "titanium black": "black",
        "titanium blue": "black",
        "natural titanium": "natural titanium",
        "desert titanium": "desert titanium",
        "deep purple": "Purple",
        "sky blue": "Blue",
        "midnight green": "Green",
        "space gray": "Grey",
        "rose gold": "Gold",
        # German to English
        "space grau": "Grey",
        "grau": "Grey",
        "gelb": "Yellow",
        "rot": "Red",
        "orange": "Orange",
        "grun": "Green",
        "grün": "Green",
        "Blau": "Blue",
        "blau": "Blue",
        "Schwarz": "Black",
        "Weiß": "White",
        "weiß": "White",
        "Grün": "Green",
        "silber": "Silver",
        "schwarz": "Black",
        "space schwarz": "Black",
        "violett": "Purple",
        "rosé": "Pink",
        "mitternacht": "Black",
        "wüstensand": "Desert Sand",
        # English variants
        "black": "Black",
        "white": "White",
        "green": "Green",
        "blue": "Blue",
        "midnight": "Black",
        "yellow": "Yellow",
        "red": "Red",
        "pink": "Pink",
        "purple": "Purple",
        "orange": "Orange",
        "grey": "Grey",
        "gray": "Grey",
        "silver": "Silver",
        "gold": "Gold",
        "starlight": "Gold",
        "graphite": "Grey",
        "titanium": "Titanium",
        "teal": "Teal",
    }
    
    return colour_map

